[package]
name = "rigid"
version = "0.1.0"
authors = ["Aymeric Beaumet <hi@aymericbeaumet.com>"]
edition = "2018"

[dependencies]
rigid_derive = { version = "=0.1.0", path = "../rigid_derive" }
rigid_runtime = { version = "=0.1.0", path = "../rigid_runtime" }
