[package]
name = "rigid_derive"
version = "0.1.0"
authors = ["Aymeric Beaumet <hi@aymericbeaumet.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
quote = "1.0.7"
rigid_runtime = { version = "=0.1.0", path = "../rigid_runtime" }
syn = "1.0.44"
